 datasource:
  type: com.alibaba.druid.pool.DruidDataSource111     1
  driver-class-name: org.gjt.mm.mysql.Driver        
  url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false6666
  username: root
  password: root
